// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (tenant_id, user_id, latitude, longitude, timestamp)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, user_id, latitude, longitude, timestamp, created_at
`

type CreateLocationParams struct {
	TenantID  pgtype.UUID        `json:"tenant_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Latitude  float64            `json:"latitude"`
	Longitude float64            `json:"longitude"`
	Timestamp pgtype.Timestamptz `json:"timestamp"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation,
		arg.TenantID,
		arg.UserID,
		arg.Latitude,
		arg.Longitude,
		arg.Timestamp,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Latitude,
		&i.Longitude,
		&i.Timestamp,
		&i.CreatedAt,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, webhook_url, api_key)
VALUES ($1, $2, $3)
RETURNING id, name, created_at, updated_at, webhook_url, api_key
`

type CreateTenantParams struct {
	Name       string      `json:"name"`
	WebhookUrl pgtype.Text `json:"webhook_url"`
	ApiKey     pgtype.Text `json:"api_key"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.Name, arg.WebhookUrl, arg.ApiKey)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WebhookUrl,
		&i.ApiKey,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (tenant_id, cognito_sub, email, role)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, cognito_sub, email, role, created_at, updated_at
`

type CreateUserParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	CognitoSub string      `json:"cognito_sub"`
	Email      string      `json:"email"`
	Role       string      `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.TenantID,
		arg.CognitoSub,
		arg.Email,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CognitoSub,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLocationsByTenant = `-- name: GetLocationsByTenant :many
SELECT id, tenant_id, user_id, latitude, longitude, timestamp, created_at FROM locations
WHERE tenant_id = $1
AND timestamp >= $2
AND timestamp <= $3
ORDER BY timestamp DESC
LIMIT $4 OFFSET $5
`

type GetLocationsByTenantParams struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Timestamp   pgtype.Timestamptz `json:"timestamp"`
	Timestamp_2 pgtype.Timestamptz `json:"timestamp_2"`
	Limit       int32              `json:"limit"`
	Offset      int32              `json:"offset"`
}

func (q *Queries) GetLocationsByTenant(ctx context.Context, arg GetLocationsByTenantParams) ([]Location, error) {
	rows, err := q.db.Query(ctx, getLocationsByTenant,
		arg.TenantID,
		arg.Timestamp,
		arg.Timestamp_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Latitude,
			&i.Longitude,
			&i.Timestamp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTenant = `-- name: GetTenant :one
SELECT id, name, created_at, updated_at, webhook_url, api_key FROM tenants
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTenant(ctx context.Context, id pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WebhookUrl,
		&i.ApiKey,
	)
	return i, err
}

const getUserByCognitoSub = `-- name: GetUserByCognitoSub :one
SELECT id, tenant_id, cognito_sub, email, role, created_at, updated_at FROM users
WHERE cognito_sub = $1 LIMIT 1
`

func (q *Queries) GetUserByCognitoSub(ctx context.Context, cognitoSub string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByCognitoSub, cognitoSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CognitoSub,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, created_at, updated_at, webhook_url, api_key FROM tenants
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListTenantsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WebhookUrl,
			&i.ApiKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
