// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetLocationsByTenant(ctx context.Context, arg GetLocationsByTenantParams) ([]Location, error)
	GetTenant(ctx context.Context, id pgtype.UUID) (Tenant, error)
	GetUserByCognitoSub(ctx context.Context, cognitoSub string) (User, error)
	ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error)
}

var _ Querier = (*Queries)(nil)
